-- MySQL Script generated by MySQL Workbench
-- 12/17/20 13:47:46
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`User` ;

CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `idUser` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Surname` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Address` VARCHAR(45) NOT NULL,
  `DateOfBirth` DATE NOT NULL,
  `Role` VARCHAR(45) NOT NULL,
  `Telephone` VARCHAR(45) NOT NULL,
  `TimeStamp` TIMESTAMP NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Category` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Category` (
  `Name` VARCHAR(255) NOT NULL,
  `Photo` BLOB NULL,
  PRIMARY KEY (`Name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Service`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Service` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Service` (
  `idService` INT NOT NULL AUTO_INCREMENT,
  `IdRequestUser` INT NOT NULL,
  `Category_Name` VARCHAR(255) NOT NULL,
  `IdPerformerUser` INT NULL,
  `Address` VARCHAR(45) NOT NULL,
  `Date` DATE NOT NULL,
  `TimeSlotIni` TIME NOT NULL,
  `TimeSlotEnd` TIME NOT NULL,
  `Deadline` DATETIME NOT NULL,
  `Details` TEXT NULL,
  `Foto` BLOB NULL,
  `Performed` TINYINT(1) NULL,
  `Assistance` TINYINT(1) NULL,
  `TimeStampInsert` TIMESTAMP NULL,
  `DateOfAcceptance` DATETIME NULL,
  PRIMARY KEY (`idService`),
  INDEX `fk_Service_User_idx` (`IdRequestUser` ASC),
  INDEX `fk_Service_User1_idx` (`IdPerformerUser` ASC),
  INDEX `fk_Service_Category1_idx` (`Category_Name` ASC),
  CONSTRAINT `fk_Service_User`
    FOREIGN KEY (`IdRequestUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Service_User1`
    FOREIGN KEY (`IdPerformerUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Service_Category1`
    FOREIGN KEY (`Category_Name`)
    REFERENCES `mydb`.`Category` (`Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
